### ISSUE TITLE
Does not work when response is in form of Array

### ISSUE THREAD

**Issue by ArunThakkar1986** [alexander-gaidukov/RESTClient#1]
Hi Alexander
First of all thanks for the wonderful code. It is really helpful. 
I've one issue here. The code worked perfectly fine (data.FlatMap) when the response is Dictionary or Key:value. 
However data.flatmap function fails mapping specially when the response is in form of Array. 
Example Link : https://data.cityofnewyork.us/resource/f9bf-2cp4.json (Array of Dictionary)
The current solution fails with mapping and returns with error "Unfortunately something went wrong"

Can you please help me to fix this issue? 
Thanks

**Comment by alexander-gaidukov** [comment]
@ArunThakkar1986 Please provide the code where you are using the library. How the Resource object looks like?

**Comment by ArunThakkar1986** [comment]
Hi Alexander. 
Thanks for your response. I've get it work. It seems in controller when you pass resource object, it should be  array. 

Thanks
